### ISSUE TITLE
Support Mobile App

### ISSUE THREAD

**Issue by Benature** [SamLewis0602/obsidian-custom-js#13]
Thanks for the excellent plugin! It would be better if the plugin support mobile app.
![image](https://user-images.githubusercontent.com/35028647/140058785-b0071809-9dfe-44bb-94fd-6eff80cf4469.png)

**Comment by SamLewis0602** [comment]
Hi, it does support mobile. That's actually the reason I wrote it in the first place 😁 can you share what you have in your file that gives you this error?

**Comment by Benature** [comment]
Hi, Here are the codes. It works well on my desktop.
```
\```dataviewjs
const {Researcher} = customJS
Researcher.display(dv)
\```
```

```js
class Researcher {
  title(p) {
    if (p.alias) {
      if (p.title.indexOf(p.alias) >= 0) {
        let t = `[[` + p.file.name + `|` + p.alias + `]]`;
        return p.title.replace(p.alias, t);
      } else {
        return `[[` + p.file.name + `|` + p.alias + `]] *|* ` + p.title;
      }
    } else {
      return `[[` + p.file.name + `|` + p.title + `]]`;
    }
  }

  d2s(t) {
    var dateformat = "MM.DD";
    return moment(t.toString()).format(dateformat);
  }

  display(dv) {
    dv.header(3, "");
    var dateformat = "MM.DD";
    dv.table(
      ["Name", "Year", "Related", "KB", "M/C"],
      dv
        .pages(`"Reading-notes" and [[` + dv.current().file.name + `]]`)
        .sort((p) => p.year, "desc")
        .map((p) => [
          this.title(p),
          p.year,
          p.related,
          (p.file.size / 1024).toFixed(1) + ``,
          this.d2s(p.file.mtime) + `\n` + this.d2s(p.file.ctime),
        ])
    );
  }
}

```

**Comment by SamLewis0602** [comment]
Try passing `moment` in as a parameter to the functions you need it in. In general you should assume that your classes don't have access to anything globally

**Comment by Benature** [comment]
Thank you for your suggestion! It works well on mobile app now.

btw, I wonder if there is a way to enable global access? So that the code in md can be simpler.

**Comment by SamLewis0602** [comment]
I wish, but unfortunately due to the limitation of not being able to `import` or `require` files on mobile prevents us from doing that. This is currently an Obsidian limitation

**Comment by SamLewis0602** [comment]
Actually, you could try using `window.moment()` and see if that works? Let me know if you try!

**Comment by Benature** [comment]
> I wish, but unfortunately due to the limitation of not being able to `import` or `require` files on mobile prevents us from doing that. This is currently an Obsidian limitation

get.



> Actually, you could try using `window.moment()` and see if that works? Let me know if you try!

I've tested, it works. Now I remove the `moment` from args.😂
