### ISSUE TITLE
dataview DataArray & customJs

### ISSUE THREAD

**Issue by melbv** [SamLewis0602/obsidian-custom-js#14]
Hi Sam
Since past update it seems that dataview api does not throw arrays anymore but only 'DataArray'. Not sure how to manipulate those in a customJS script? The functions attached to them in dataview do not seem to be working in the script by simply calling them (array.function()). How can i use those?
Thanks in advance

**Comment by SamLewis0602** [comment]
Hi melbv. Can you share a code example?

**Comment by melbv** [comment]
Hi Sam

Dataview switched the output of their queries to becoming a proprietary dataarray type (https://blacksmithgu.github.io/obsidian-dataview/api/data-array/) with properties attached to the object.
After having tested a few days ago, i did not seem to be able to use the functions attached to the dataarray type (see the bottom of the page in the link).

Certain API let you create an object that inherit all the properties of their native objects (examples below) and was wondering whether the same could be achieved with that new dataarray object.


```
const { exampleClass} = customJS
const { update } = app.plugins.plugins["metaedit"].api
etc...
```

**Comment by SamLewis0602** [comment]
The example code you gave is an example of a javascript concept called destructuring. The following two lines are identical:
```
const { exampleClass} = customJS
const exampleClass = customJS.exampleClass
```

With that being said, I'm still not exactly sure what you're trying to do. Can you paste the code/dataview block you're running that's not working? From what I see in the docs you linked, DataArrays add additional functions, so you should be able to do anything you can do with an Array with a DataArray

**Comment by KjellConnelly** [comment]
I know from experience that dataviewjs made some breaking changes recently when it comes to arrays. For example, I used to be able to do something like:

```javascript
const pages = dv.pages('-"Templates"').where(p=>{
    return p["for whom"].reduce((response, name)=>{
    	return response || name.toLowerCase().includes(filenameLowerCase)
    }, false)
})
```

in this example, `p["for whom"]` used to be treated as a regular array (or at least I assume). But then after the update, there was no `reduce` function available. So now it goes `p["for whom"].values.reduce(...`

It's possible you're trying to do something like this, in which case I'd try to write the function in the markdown file first, and have the Javascript developer console open. Then you can search for alternatives that work. That's how I figured out that I can't use `reduce` anymore and now have to do `values.reduce`

**Comment by melbv** [comment]
Hi @SamLewis0602  within the code, i am trying to test for a dataarray i.e.
`if (array instanceof DataArray) {}`
For the moment, i can only see the array as an instance of an object (which is not precise enough in my view). I was wondering if there is a way to write a test to identify a dataarray specifically.
Hope this makes more sense?

**Comment by melbv** [comment]
@KjellConnelly you are basically using the dataarray as a js object instance - i would like to see if i can treat a dataarray as intended by dataview - if it makes any sense.
You should be able to replace `.values.reduce` with `.filter` according to dataview

**Comment by SamLewis0602** [comment]
Sorry, what is your actual problem? Are you finding that using `.filter` isn't working? I'm confused why you are testing if something is an instance of dataarray when you mentioned earlier that it's always a dataarray.

**Comment by SamLewis0602** [comment]
A code example and error would make this much smoother if you can provide that @melbv

**Comment by melbv** [comment]
Hi Sam

Sorry for the confusion. To re-order the thread:

To your second point on a code example:
Below is a function i use to compare 2 datapoints that can be anything: a DataArray, a Date or any type (string, number, else...).
The code works as is today but testing for an object and not a dataarray has limitations are it captures object instances that may not be dataarrays.

```
DataCheck(arg1, arg2) {
		
		let tempresult = false
		let iarg1 = arg1
		let iarg2 = arg2
		
		switch(true) {
			case Boolean(arg1.isValid):
			case Boolean(arg2.isValid):
			case (!(iarg2 instanceof Object) && !(iarg1 instanceof Object)):
				tempresult = this.compareData(iarg1, iarg2)
			break;
			case (!(iarg1 instanceof Object)):
				for (let i = 0; i < iarg2.length; i++) {
				tempresult = tempresult || this.compareData(iarg1, iarg2[i])
				}
			break;
			case (!(iarg2 instanceof Object)):
				for (let i = 0; i < iarg1.length; i++) {
				tempresult = tempresult || this.compareData(iarg1[i], iarg2)
				}
			break;
			default:
				for (let i = 0; i < arg2.length; i++) {
					for (let j = 0; j < arg1.length; j++) {
						tempresult = tempresult || this.compareData(iarg1[j], iarg2[i])
					}
				}
			break;
		}
		
		return tempresult
	}
```

hope this makes sense

to the first point on retesting, using `.filter` seems to work fine!

**Comment by SamLewis0602** [comment]
Ah, your confusion may be that in javascript, an array is an object. Try using `Array.isArray()` to check if something is an array

**Comment by melbv** [comment]
The problem is that array.isArray() does not capture the dataarray instance which is proprietary to dataview... but thanks for looking into it. 
Hopefully dataview (or its documentation) will evolve to cover how to identify specifically a dataarray

15 Nov 2021, 15:58 by ***@***.***:

**Comment by SamLewis0602** [comment]
Yeah you should open an issue on the dataview repository, this isn't a CustomJS issue

**Comment by melbv** [comment]
Sure - thanks Sam for your time
