### ISSUE TITLE
Folder Settings Not Loading?

### ISSUE THREAD

**Issue by asauceda94** [SamLewis0602/obsidian-custom-js#15]
Howdy! Not sure if I'm just misunderstanding the README or doing something incorrectly, but I can't for the life of me get scripts to load if I use only the folder setting and not the individual scripts setting. I'll attach the file I'm currently testing in below:
[} Migrate Queries to CustomJS Plugin.md](https://github.com/SamLewis0602/obsidian-custom-js/files/7515589/Migrate.Queries.to.CustomJS.Plugin.md)

I initially tried setting up the "scripts" folder in my .obsidian folder, then in the Vault root, then tried pointing to it from my computer's root directory, but I am still unable to get scripts from a folder to work.

Additionally, I don't see any information - positive or negative - in the console when I utilize only the folder setting. It shows CustomJS loading, then nothing, but when I try to render to Preview, I get the good ol' `TypeError` problem. Any advice on what I may be doing wrong?

**Comment by SamLewis0602** [comment]
That syntax is outdated. On the latest version of CustomJS, change

`const {CoolString} = app.plugins.plugins.customjs`

to

`const {CoolString} = customJS`

See the README for the most up to date examples.
