### ISSUE TITLE
Can't Import File

### ISSUE THREAD

**Issue by asauceda94** [SamLewis0602/obsidian-custom-js#16]
Hello!

I am getting this error when attempting to use the plugin:
`main.ts:65 SyntaxError: Missing initializer in destructuring declaration
    at CustomJS.eval (eval at <anonymous> (app.js:1), <anonymous>:207:45)
    at Generator.next (<anonymous>)
    at fulfilled (eval at <anonymous> (app.js:1), <anonymous>:28:58)
`
Attaching my code as .txt:
[dvTasks.txt](https://github.com/SamLewis0602/obsidian-custom-js/files/7547713/dvTasks.txt)

I've tried changing a few different things, but to be frank I don't quite understand the error - not sure if this is a me issue (likely) or a plugin issue.

**Comment by SamLewis0602** [comment]
Check line 86, you forgot `= args` after your destructuring
