### ISSUE TITLE
FEATURE: support ts files 

### ISSUE THREAD

**Issue by alexn-s** [SamLewis0602/obsidian-custom-js#18]
It would be really nice if this extension also directly supports typescript files.

Perhaps with this:
[Official TypeScript compiler API transform](https://github.com/Microsoft/TypeScript-wiki/blob/main/Using-the-Compiler-API.md#a-simple-transform-function)

or some bundler setup, shell, npm module config

## propose
new fields in extension settings to support ts folder and of course backend support for the functionality

**Comment by SamLewis0602** [comment]
I've actually tried that exact API, but it was failing in Obsidian. Happy to review a PR if you're able to figure it out.

**Comment by alexn-s** [comment]
Interesting, i will take a look at it. at least resort i will transpire them on the run, although i am not sure about how that will affect mobile
