### ISSUE TITLE
Possible to pass in a constructor argument to a class when using CustomJS?

### ISSUE THREAD

**Issue by tekiegirl** [SamLewis0602/obsidian-custom-js#20]
Is it possible to pass in a parameter to a constructor in a class when using CustomJS?
I don't use JS that much, so apologies if this is silly/obvious to you :)

I would like to pass in the DataView dv object to the class to avoid having to pass in dv to any functions that need to use it, so that is the use case.
I have tried doing this but get errors if I do anything except 
`const {ClassNameOnly} = customJS;`

Many thanks :)

**Comment by SamLewis0602** [comment]
You have a good instinct! Generally speaking, in JS that would be a better way to do it. However, until Obsidian can support regular imports on mobile (this is likely more difficult than it sounds), I'm forced to use `eval` which is why the customJS usage is so restrictive in general (one class per file, etc). 

All that to say, it isn't possible to allow users to pass anything to the constructor directly. A possible way to support common plugins like dataview would be to allow users to set whether they want it passed in the settings. But I don't have the time to test it out right now unfortunately. If I find time to try it later I will, but for now you'll have to pass it to each method as you mentioned.

**Comment by jbiros91** [comment]
Hi, you can set instance fields via setters. 

```
class Foo {
    plusOne = nul

    setPlusOne(myField) {
        this.plusOne = plusOne
        return this
    }

    getTwo() {
        return 1 + this.plusOne
    }

   getThree() {
        return this.getTwo() + this.plusOne
   }
}
```

Then use it like:
```dataviewjs

const fooInstance = customJS.Foo.setPlusOne(1)

fooInstance.getTwo() // returns 2

fooInstance.getThree() // returns 3

```

**Comment by SamLewis0602** [comment]
Thanks @jbiros91 ! That's a cool idea. Adds one line of boilerplate to a `dataviewjs` block, but saves you from having to pass  objects to every method. Seems like a good compromise.

**Comment by cabbage** [comment]
Another way is to use the class as a module or name-space and define classes as fields with the [`class` expression](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/class).

```javascript
class MyModule {
  MyClass = class {
    constructor(param) {
      this.myField = param
    }
  }
}
```
Usage:
```javascript
const { MyModule } = customJS
const myInstance = new MyModule.MyClass('foo')
```

You can even inherit from classes within your module (define super-classes before you extend from them; there's no hoisting here AFAIK)

---

A little more involved example using [Templater's dynamic command](https://silentvoid13.github.io/Templater/commands/dynamic-command.html):
```javascript
// my-module.js
class MyModule {
  MyClassA = class {
    constructor(param) {
      this.myField = param
      console.debug(
        `${this.constructor.name} constructor called with param-value ${param}.`,
      )
    }
  }

  MyClassB = class extends this.MyClassA {
    constructor(param, otherParam) {
      super(param)
      this.myOtherField = otherParam
      console.debug(
        `${this.constructor.name} constructor called with otherParam-value ${otherParam}.`,
      )
    }
  }

  constructor() {
    console.debug('MyModule initialized.')
  }
}
```

```javascript
// my-module.test.js
class MyModuleTest {
  run() {
    const { MyModule } = customJS
    
    const instanceA = new MyModule.MyClassA('foo')
    const instanceB = new MyModule.MyClassB('bar', 'baz')
  }
}
```

```markdown
<!-- templater-test.md -->
MyModule Test <%+ customJS.MyModuleTest.run() %>
```
Expected console output (level verbose/debug):
```
MyModule initialized.
MyClassA constructor called with param-value foo.
MyClassB constructor called with param-value bar.
MyClassB constructor called with otherParam-value baz.
```

**Comment by SamLewis0602** [comment]
Ah the nested classes are a great idea, I'll leave this issue open so it's easier for others to find.

**Comment by tekiegirl** [comment]
Thanks all for the great input!

**Comment by SamLewis0602** [comment]
Arguably a bit odd to advertise a "competing" OSS project in an issue, but I don't actually use Obsidian anymore and have just been maintaining this for the users so it's cool. Gonna close this issue though since the conversation has now strayed from the original focus.

**Comment by cstrahan** [comment]
I was thinking maybe we'd merge (the good bits) of mine into yours -- didn't intend to steamroll you.

Thanks for maintaining your project, despite stepping away from Obsidian :pray:

**Comment by SamLewis0602** [comment]
Definitely open to collaboration, I just merged in a PR from someone a week or two ago. Exciting to know people are using the plugin!

Feel free to open a new issue and we can discuss how the two plugins may be able to work together.
