### ISSUE TITLE
this seems awesome, can one use this to always open a note default in preview mode?

### ISSUE THREAD

**Issue by zeltak** [SamLewis0602/obsidian-custom-js#22]
Hi

this is sweet

i have zero coding experience but can this be used to always open a note bgu default in preview mode?

ie lets say note `example.md` is owned while the overall mode is `editing` can this auto change `example.md` to preview mode?

thx so much

Z

**Comment by SamLewis0602** [comment]
https://forum.obsidian.md/t/always-open-in-preview-mode-settings-option/12484/2
