### ISSUE TITLE
How to access methods from other files?

### ISSUE THREAD

**Issue by stecydube** [SamLewis0602/obsidian-custom-js#25]
Let's say I have two files:

```js
// a.js
class a {
    someFunc() {
        b.otherFunc(); // This is what I want to achieve
    }
}
```

```js
// b.js
class b {
    otherFunc() {
    }
}
```

How to access methods from another file?

**Comment by stecydube** [comment]
Tried everything and got no success and out of despair I tried simply:

```js
class a {
    someFunc() {
        const {b} = customJS;
        b.otherFunc();
    }
}
```

That's so meta 😆

**Comment by SamLewis0602** [comment]
Hah! That's funny. I wouldn't have thought to try that, but it does make sense. I believe that's the only way you can reference another file. You could also have `someFunc` take `b` as a parameter and pass it in from your obsidian note, but I think your solution is better :P
