### ISSUE TITLE
How can I use require statement?

### ISSUE THREAD

**Issue by EgeCaglarDurmaz** [SamLewis0602/obsidian-custom-js#26]
I tried to install a module and 'require' at the js file. It didn't work. I got an error. Is there any solution?

$ cd scripts
$ npm install ramda

// in vault at scripts/coolString.js
R = require('ramda')
class CoolString {
    coolify(s) {
        return `😎 ${s} 😎`
    }
}

**Comment by SamLewis0602** [comment]
Hi, you can't `require` in customJS. Until Obsidian changes the api we have to `eval` javascript code which means only browser-native JS.

**Comment by EgeCaglarDurmaz** [comment]
Hi, my workaround is to use browserify. Below is for the ramda.js module. If anyone has a better solution, I'd love to hear it.

STEP 1: browserify  one line of code with a 'require' statement

sudo npm install -g browserify
mkdir coolModuleRamda
cd coolModuleRamda
npm init -y
npm i ramda
touch index.js
echo 'coolModule = require("ramda");' >> in.js
browserify in.js -o out.js

STEP 2: Create a class similar to the one below. Copy the text of out.js and paste it after the comment line.

class CoolModules{
    constructor() {
        this.R = null;
    }
    ramda(){
        if (!this.R){
            let coolModule;
             //  PASTE THE CODE HERE
            this.R = coolModule;
        }
        return this.R;
    }
}
