### ISSUE TITLE
Feature request: CustomJS in hidden folder

### ISSUE THREAD

**Issue by ramisedhom** [SamLewis0602/obsidian-custom-js#27]
Is it possible to allow CustomJS to access javascript files in hidden folder (folder start with '.')?

I've tried it but CustomJS, for some reason, can't detect the hidden folders.

**Comment by SamLewis0602** [comment]
I haven't tried it, but if it doesn't work then it would be an Obsidian limitation since CustomJS uses Obsidian APIs to read the file.

**Comment by ramisedhom** [comment]
I think it's possible if `loadClasses` start from `app` base path:
`this.app.fileManager.vault.adapter['basePath'] + this.settings.jsFolder`
instead of using Obsidian APIs to get files:
`this.app.vault.getFiles();`

Do you want me to try doing it? or you prefer the current way?

I believe that CustomJS ability to be in hidden folder is a plus to hide scripting folder from Obsidian File Explorer.

**Comment by SamLewis0602** [comment]
`this.app.fileManager.valut.adapter['basePath']` will break on iOS and Android, that's why the other API is currently used.

**Comment by SamLewis0602** [comment]
That said, feel free to experiment and submit a PR if you get something working. Just make sure to test on desktop and mobile.
