### ISSUE TITLE
Executing code does not work on Obsidian Mobile 0.1.2 (iOS)

### ISSUE THREAD

**Issue by PhilipJonasFranz** [SamLewis0602/obsidian-custom-js#28]
Obsidian Mobile iOS version: 1.2.0

Executing code imported from external *.js file is not able to execute. Executed code is known to work on Obsidian Desktop (0.14.5). 

The code is executed in a dataviewjs codeblock and results in the following error:

```Evaluation Error: eval code@
eval@[native code]
@
@
asyncFunctionResume@[native code]
@
asyncFunctionResume@[native code]
onload@
@capacitor://localhost/app.js:1:643791
@capacitor://localhost/app.js:1:644213
@
asyncFunctionResume@[native code]
asyncFunctionResume@[native code]
@capacitor://localhost/app.js:1:834442
@capacitor://localhost/app.js:1:1512474
@capacitor://localhost/app.js:1:1511300
h@capacitor://localhost/app.js:1:822622
@capacitor://localhost/app.js:1:822872
@[native code]

**Comment by PhilipJonasFranz** [comment]
I was referring to a `js`-file which i wrote and then used in a Dataviewjs-Block. The file was imported using the `const { MyFile } = customJS` syntax. The code was similar to the advanved example given on the README. The file was nothing special and does not use any other libaries. I was using it to reduce duplicated code over multiple different markdown files. The import with the plugin works on Desktop, but crashes on Mobile.

**Comment by PhilipJonasFranz** [comment]
A minimal example of this issue would be:

Markdown file:
~~~markdown
# Example
```dataviewjs
const { DataviewCommons } = customJS
dv.span(DataviewCommons.getMessage());
```
~~~

JS-File:
~~~js
class DataviewCommons {
    getMessage() {
        return "Hello World!";
    }
}
~~~

In the Plugin Settings, the file is listed as individual file. Im running iOS `15.3.1`.

**Comment by SamLewis0602** [comment]
Thanks for the info, I'll try to reproduce and get back to you.

**Comment by SamLewis0602** [comment]
I can't reproduce it. I updated dataview to the latest version as well just to be sure. Obsidian 1.2.0. I tested your code and verified my tasks set up was still working.

`scripts/dataview-common.js`
![image](https://user-images.githubusercontent.com/15079088/163299956-32af11a4-35a0-4f1a-8b61-289cf9e83e5a.png)


CustomJS individual file setting:
scripts/dataview-common.js

And two iOS screenshots using it in a markdown file:
![D1470B08-F753-419D-B0F5-6C37BAF7261F](https://user-images.githubusercontent.com/15079088/163299864-14badb3d-c361-46ca-ab39-aa1d77aec264.PNG)
![D0045719-EAB3-4E74-BEAA-F05E0A08F1DA](https://user-images.githubusercontent.com/15079088/163299872-68b118ea-b2ec-47d4-b121-be1f2d056675.PNG)

**Comment by PhilipJonasFranz** [comment]
Interesting. I managed to produce it on my device again and disabled all plugins except CustomJS and Dataview just to be sure. 

Which iOS version are you running?

Could it be possible that my iOS Safari Settings could interfere with the plugin?

**Comment by PhilipJonasFranz** [comment]
I have figured out the issue. Turns out i was writing the filepath to my script using backslashes instead of regular slashes. Having changed that it works perfectly. I would guess that you wrote the path using slashes?

**Comment by SamLewis0602** [comment]
Thanks for following up. I'll add a note to the readme
