### ISSUE TITLE
`customJS` is Not Defined in Templater Startup Template

### ISSUE THREAD

**Issue by iamrecursion** [SamLewis0602/obsidian-custom-js#29]
I recently embarked on a refactor of my templates, but it seems that adding more than two `.js` files into my custom-js folder means that `customJS` is no longer defined when called from templater's startup template. If I remove the third `.js` file it suddenly works again. Dataview seems to be unaffected.

**Comment by iamrecursion** [comment]
In my case, custom JS is the first plugin to load, and doesn't display any errors in console when loading.

**Comment by iamrecursion** [comment]
Are the `.js` files loaded synchronously at plugin load time or is it possible that this is a race condition?

**Comment by iamrecursion** [comment]
Preliminary debugging looks like a race condition. While `loadClasses` starts to run before templater runs its startup script, `window.customJS` doesn't seem to be set until afterward.

```
RUNNING loadClasses
Templater Error: Startup Template parsing error, aborting. 
 customJS is not defined
CUSTOMJS: Setting handle on window
```

The prints were added as follows:

```typescript
  async loadClasses() {
    console.log("CUSTOMJS: Running loadClasses");
    const customjs = {};
    const filesToLoad = [];

    // <snipped>

    // load all scripts
    for (const f of filesToLoad) {
      await this.evalFile(f, customjs);
    }

    console.log("CUSTOMJS: Setting handle on window");
    // @ts-ignore
    window.customJS = customjs;
  }

**Comment by iamrecursion** [comment]
For my own purposes I've added:

```typescript
    // @ts-ignore
    window.forceLoadCustomJS = async () => {
      await this.loadClasses();
    };
```

Which can be used in the startup template as `await forceLoadCustomJS()`. It's a total hack, but I'm happy to PR it if there's not a better way!

**Comment by SamLewis0602** [comment]
Thanks for taking the time to debug! Can you share how you're using Templater here? I'm not very familiar with it. I looked at the docs but couldn't find anything when looking for "startup template". Once I understand the use case we can see if there's a better solution to the problem or get a PR going with your solution 😁

**Comment by iamrecursion** [comment]
I don't know if it's mentioned in the docs at all, but in the settings for templater there's a section "startup templates". Essentially, a startup template is one that is executed when Obsidian starts up (see [here](https://github.com/SilentVoid13/Templater/blob/097c7c0c99dc9f6932af6d44df9ebccfd995c4b3/src/core/Templater.ts#L419)). These are fired (as mentioned above) from the `onLayoutReady` event, much like `customJS` is evaluated and bound there, and as both of those callbacks are `async` and don't get `await`ed, it's possible (and happens) that these two race. 

Does that make sense? ^^

**Comment by SamLewis0602** [comment]
Hm I'm not familiar with the startup template but I think your workaround is the best way to go since it's ultimately a race condition between Templater loading and CustomJS loading.

**Comment by SamLewis0602** [comment]
Oh I missed your above comment explaining the situation haha, yes that does make sense. So I don't think it's something that can be fixed in the plugin itself, unless there's some way to tell Obsidian which plugins should be loaded first and ignores it if not installed. Not sure if that exists or not.

**Comment by iamrecursion** [comment]
To my knowledge there's no way to express dependencies between plugins in the API. Even if there were, I don't think it would extend to events firing `onLayoutReady`, which makes the whole thing a wash anyway. 

Shall I PR this hacky fix?

**Comment by SamLewis0602** [comment]
That'd be great!

**Comment by iamrecursion** [comment]
PR filed in #30.
