### ISSUE TITLE
Reference error at Obsidian startup

### ISSUE THREAD

**Issue by oliviercarizzoni** [SamLewis0602/obsidian-custom-js#32]
Hi,

Since the last update, I have a reference error at startup for customJS object on the first page displayed (homepage for me).

I need to edit the block, or to change page and go back to it to resolve the error, did you see that issue?

Regards, Olivier

![referenceError](https://user-images.githubusercontent.com/36270849/172067520-240a72f2-fdae-4869-9a59-bd981cb1051b.png)

**Comment by SamLewis0602** [comment]
CustomJS works normally for me on the latest Obsidian update v0.14.15

Can you open developer tools after starting Obsidian and see if there are any errors in there? It's Cmd + option + i on mac and ctrl + alt + i on windows

**Comment by oliviercarizzoni** [comment]
Hi, thanks for the answer, sadly there is nothing showing up in the console, I just can't be the only one having that issue :

![Obsidian_bVZdrcArgc](https://user-images.githubusercontent.com/36270849/174608248-a4c72e6d-0710-4737-b243-93b74131dd6a.png)

Minor issue since I can quickly revert it to normal but annoying.

**Comment by SamLewis0602** [comment]
Sorry, there isn't anything I can do without any logs and unable to reproduce it. I'll leave the issue open in case others have it too.

**Comment by toroworx** [comment]
I had that as well, it was user error on my case. You can fix it by specifying the full path at 'Individual files' of CustomJS settings (`scripts/coolString.js` in this case if you follow the example). Then make sure the javascript file only contains: 

```
// in vault at scripts/coolString.js
class CoolString {
    coolify(s) {
        return `😎 ${s} 😎`
    }
}
```

And the .md file only contains:

    ```dataviewjs
    const {CoolString} = customJS
    dv.list(dv.pages().file.name.map(n => CoolString.coolify(n)))
    ```

Don't forget to restart Obsidian.

**Comment by SamLewis0602** [comment]
What did you have in your settings when you saw the error?

**Comment by toroworx** [comment]
The 'Individual files' setting, remove the relative path and only input the file. For my case:
`.obsidian/scripts/coolString.js` works, but `coolString.js` gives the error:

```
Evaluation Error: TypeError: Cannot read properties of undefined (reading 'coolify')
    at eval (eval at <anonymous> (plugin:dataview), <anonymous>:2:50)
    at Array.map (<anonymous>)
    at Proxy.map (plugin:dataview:9415:39)
    at eval (eval at <anonymous> (plugin:dataview), <anonymous>:2:30)
    at DataviewInlineApi.eval (plugin:dataview:19597:16)
    at evalInContext (plugin:dataview:19598:7)
    at asyncEvalInContext (plugin:dataview:19608:32)
    at DataviewJSRenderer.render (plugin:dataview:19629:19)
    at DataviewJSRenderer.onload (plugin:dataview:19213:14)
    at DataviewJSRenderer.e.load (app://obsidian.md/app.js:1:730611)
```

I see the error is not exactly the same. I can replicate and fix @oliviercarizzoni's error `Evaluation Error: ReferenceError: customJS is not defined` by simply enabling/disabling the `CustomJS` plugin at the Community plugins page. I think he forgot to enable the plugin?

**Comment by oliviercarizzoni** [comment]
Thx for the replies guys, I have just looked back at documentation and it seems that one instruction `await forceLoadCustomJS()` placed before the first snippet does the trick and solve that issue ! Thx @SamLewis0602 !

Seeing @toroworx comment, i tried to use scripts located in `.obsidian` with folder setting, and got the TypeError above. However this works fine for individual files settings.

Regards, Olivier

**Comment by SamLewis0602** [comment]
@toroworx for the record, the path has nothing to do with the .obsidian folder. You can put a `.js` file anywhere you want in your vault and use it. So it's not really a question of relative vs full path, but rather all paths are relative to the root of your vault.

**Comment by toroworx** [comment]
Thanks for the clarification. I understand and agree, I didn't explain it properly.
You'll have to enter the path relative to the vault indeed. Omitting the path gives the error. And, I didn't test it, but it probably indeed doesn't have anything to do with the .obsidian folder. Probably not the best practise to store in that reserved folder though, I'll use another folder from now on. I supplied that folder information to be complete about the error report.
