### ISSUE TITLE
Error on import

### ISSUE THREAD

**Issue by ahershey21** [SamLewis0602/obsidian-custom-js#33]
All scripts have the same error on loading. They still seem to function OK, but error appears to be in customjs.
I have pasted images of the errors:

![image](https://user-images.githubusercontent.com/40613263/176965218-0372c67e-5976-463c-b12d-6b49c95868b8.png)

**Comment by SamLewis0602** [comment]
Can you share what you have in your customJS settings?

**Comment by ahershey21** [comment]
Here you go:

![image](https://user-images.githubusercontent.com/40613263/177769941-85565886-a066-4ae5-bba8-8a99e3202dd2.png)

**Comment by SamLewis0602** [comment]
And can you also share `index1.js`?

**Comment by Jonon** [comment]
I have the exact same problem. I have checked if the naming and the path is correct. It basically loads the document but I still get this error. Do I need something specific in the JS document to set it up correctly?

**Comment by ahershey21** [comment]
I deleted index1.js (removed first without any impact and I wasn't using anymore.

**Comment by ahershey21** [comment]
Note that this happens for all of the .js,  I just used the index1.js above as an example.

**Comment by ahershey21** [comment]
Found a back up, here is the script:

import React from "react";
import ReactDOM from "react-dom";
import CalendarHeatmap from "react-calendar-heatmap";
import ReactTooltip from "react-tooltip";

import "react-calendar-heatmap/dist/styles.css";
import "./styles.css";

const today = new Date();

function App() {
  const randomValues = getRange(200).map((index) => {
    return {
      date: shiftDate(today, -index),
      count: getRandomInt(0, 3)
    };
  });
  return (
    <div>
      <h1>react-calendar-heatmap demos</h1>
      <p>Random values with onClick and react-tooltip</p>
      <CalendarHeatmap
        startDate={shiftDate(today, -150)}
        endDate={today}
        values={randomValues}
        classForValue={(value) => {
          if (!value) {
            return "color-empty";
          }
          return `color-github-${value.count}`;
        }}
        tooltipDataAttrs={(value) => {
          return {
            "data-tip": `${value.date.toISOString().slice(0, 10)} has count: ${
              value.count
            }`
          };
        }}
        // transformDayElement={(element, value, index) => React.cloneElement(element, { title: value.date })}
        showWeekdayLabels={true}
        onClick={(value) =>
          alert(`Clicked on value with count: ${value.count}`)
        }
      />
      <ReactTooltip />
    </div>
  );
}

function shiftDate(date, numDays) {
  const newDate = new Date(date);
  newDate.setDate(newDate.getDate() + numDays);
  return newDate;
}

function getRange(count) {
  return Array.from({ length: count }, (_, i) => i);
}

function getRandomInt(min, max) {
  return Math.floor(Math.random() * (max - min + 1)) + min;
}

const rootElement = document.getElementById("root");
ReactDOM.render(<App />, rootElement);

**Comment by SamLewis0602** [comment]
You can't use any libraries with CustomJS. It's an Obsidian limitation. You can't use any `import` statements at all. Check the docs to see the proper format for a CustomJS file. Each file must contain a single JS class and nothing else. Again, this is an Obsidian limitation that can't be worked around, though you are welcome to try. PRs welcome if you're successful.
