### ISSUE TITLE
Reference multiple files together

### ISSUE THREAD

**Issue by carlonicora** [SamLewis0602/obsidian-custom-js#34]
Hello,

First and foremost **thanks** for publishing this plugin, it is very useful!

One quick question. I have the need to use (at least) two separate classes together. Let's call them **A** and **B**. The goal is for A to instantiate and keep a copy of **B** in itself.

```
class A{
  initialise(){
    b = new B();
  }
}

class B{
}
```

I tried to use two separate files or place the two classes in the same file, but no matter what I have tried so far, I am unable to instantiate class B form A.

Either I get that B is not defined (when I use two separate files, or I get a TypeError (Cannot read properties of undefined) which is caused by the fact that CustomJS cannot import a script with two classes.

Any suggestions?

Thanks

**Comment by carlonicora** [comment]
I manage to find out the answer...

```
window.customJS.CLASSNAME
```

**Comment by SamLewis0602** [comment]
Also, see the note in the README about how classes are loaded in Alphabetical order by class name.

**Comment by carlonicora** [comment]
Thanks @SamLewis0602
