### ISSUE TITLE
Access the Obsidian API?

### ISSUE THREAD

**Issue by b0o** [SamLewis0602/obsidian-custom-js#35]
I want to call the Obsidian [`MarkdownRenderer.renderMarkdown`](https://github.com/obsidianmd/obsidian-api/blob/6b2138aa28fb6d6f58f78e6fabec02186fdc0f82/obsidian.d.ts#L2008) function - is there a way to do this from CustomJS?

**Comment by panahi** [comment]
You can access the API via window.app

**Comment by SamLewis0602** [comment]
Thanks @panahi. That's correct 😁

**Comment by saml-dev** [comment]
PRs welcome, even just for documentation
