### ISSUE TITLE
Support TS files

### ISSUE THREAD

**Issue by nkoder** [SamLewis0602/obsidian-custom-js#4]
I think it might be valuable to support`.ts` files too. My case is to have type assistance in my IDE thanks to TS extension:
<img width="717" alt="Screen Shot 2021-09-12 at 13 15 00" src="https://user-images.githubusercontent.com/612936/132985379-baaf94ee-afaa-4f09-ab07-ca3da1c2b43d.png">

I managed to achieve TS support in CustomJS by editing plugin's file locally, but OFC it will become lost once I update CustomJS to the next version 🙂 

I might want to try creating a Pull Request to address this issue.

**Comment by SamLewis0602** [comment]
Please do open a PR! I'd be happy to take a look.

**Comment by SamLewis0602** [comment]
@nkoder also feel free to just share your main.js with your enhancements and I'd be happy to help get it worked into the plugin. I'm curious to see how you got it working, I tried to use this strategy but it kept blowing up saying `_os.platform is not a function`

```js
import * as ts from 'typescript';
const js = ts.transpile(tsString);
```

**Comment by nkoder** [comment]
ah, sorry, I mislead you, because I wrongly assumed it works for me 😅  Looks like I was thinking TS is working with my changes to CustomJS codebase, but I think what happened was Obsidian still using my scripts from before I added types to them (like `: string`).

Long story short: it doesn't work for me, so I have nothing to share 🤷‍♂️

**Comment by SamLewis0602** [comment]
Ahh no worries! If you're using dataview, feel free to follow along on this issue as I'm trying to make it seamless for the user when you update your CustomJS code.

https://github.com/blacksmithgu/obsidian-dataview/issues/482
