### ISSUE TITLE
How to reload a script

### ISSUE THREAD

**Issue by renarl** [SamLewis0602/obsidian-custom-js#5]
How do you reload a custom js script while you are still working on it? Currently, I'm restarting the obsidian, but this takes very long.

**Comment by SamLewis0602** [comment]
CustomJS actually reloads your scripts automatically as soon as you save the file. However, if you're using dataview — or maybe templater, not sure as I don't use it — it caches the result of your input inside a `dataviewjs` block. So, to get it to rerun your code, just add/delete a space from your `dataviewjs` block and it will run your code again. I'm going to work with the author of dataview to see if there's a way I could selectively clear a file out of its cache when users change their CustomJS files.

**Comment by SamLewis0602** [comment]
I've opened this issue in the dataview repo to work with the author to try to find a fix, feel free to follow along there!

https://github.com/blacksmithgu/obsidian-dataview/issues/482

**Comment by SamLewis0602** [comment]
Update: waiting for the next release of dataview which includes an API I can use to automatically update Dataviews when CustomJS scripts change

**Comment by SamLewis0602** [comment]
Version [1.0.10](https://github.com/SamLewis0602/obsidian-custom-js/releases/tag/1.0.10) has been released that automatically reloads `dataviewjs` blocks whenever a CustomJS script is changed. Be sure to update `dataview` to the latest version as well!
